In [8]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer as si


In [9]:
# Load the dataset
data=pd.read_csv(r'D:\Python Projects\csv\book1.csv')
print(data)

            Item   Cost    Sold  Profit
0       Keyboard   10.0     NaN     NaN
1        Monitor    NaN   120.0     NaN
2          Mouse    5.0     7.0     2.0
3    cooling pad   10.0     NaN     NaN
4    motherboard   50.0    45.0    -5.0
5            gpu  500.0  1000.0   500.0
6            cpu  250.0   300.0    50.0
7   power supply    NaN    96.0     NaN
8          wires   15.0     NaN     NaN
9           fans    NaN    24.0     NaN
10         Total  840.0  1592.0   547.0


In [10]:
# Identify missing data (assumes that missing data is represented as NaN)
change=si(missing_values=np.NaN)
# Print the number of missing entries in each column
print(change)

SimpleImputer()


In [11]:
# Configure an instance of the SimpleImputer class
change=si(missing_values=np.NaN, strategy='mean')
col=data.columns[1:]

In [12]:
# Fit the imputer on the DataFrame
change.fit(data[col])

SimpleImputer()

In [13]:
# Apply the transform to the DataFrame
data=change.transform(data[col])

In [14]:
#Print your updated matrix of features
print(data)

[[  10.   398.   218.8]
 [ 210.   120.   218.8]
 [   5.     7.     2. ]
 [  10.   398.   218.8]
 [  50.    45.    -5. ]
 [ 500.  1000.   500. ]
 [ 250.   300.    50. ]
 [ 210.    96.   218.8]
 [  15.   398.   218.8]
 [ 210.    24.   218.8]
 [ 840.  1592.   547. ]]


In [19]:
from sklearn.compose import ColumnTransformer as ct
from sklearn.preprocessing import OneHotEncoder as ohe
trans=ct(transformers=[('encoder', ohe(),[0])],remainder='passthrough')
data=np.array(trans.fit_transform(data))

In [20]:
print(data)

[[ 0.000e+00  1.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   0.000e+00  0.000e+00  3.980e+02  2.188e+02]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  1.000e+00  0.000e+00
   0.000e+00  0.000e+00  1.200e+02  2.188e+02]
 [ 1.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   0.000e+00  0.000e+00  7.000e+00  2.000e+00]
 [ 0.000e+00  1.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   0.000e+00  0.000e+00  3.980e+02  2.188e+02]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00  0.000e+00  0.000e+00
   0.000e+00  0.000e+00  4.500e+01 -5.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
   1.000e+00  0.000e+00  1.000e+03  5.000e+02]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  1.000e+00
   0.000e+00  0.000e+00  3.000e+02  5.000e+01]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  1.000e+00  0.000e+00
   0.000e+00  0.000e+00  9.600e+01  2.188e+02]
 [ 0.000e+00  0.000e+00  1.000e+00  0.000e+00  0.000e+00  0.000e+00
   0.000e+00